spring:
  datasource:
    url: jdbc:mysql://104.154.103.86:3306/uwmdb
    username: uwm
    password: uwmdb4beta
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

datasource:
  hibernate:
    dialect:
      org.hibernate.dialect.MySQL5Dialect‎